/* ============================================================
   LEGO Spelling Blocks — English word ladder (Grade 1 → 6+)
   Each entry: { w, lvl, e?, cat?, tags? }
   - w: word (lowercase)         - lvl: 1..6
   - e: emoji (omit for abstract → voice-first spell card)
   - cat: category               - tags: homophone|silent|double|prefix|suffix
   This is a solid starter ladder, structured to expand toward ~2-3k words.
   ============================================================ */
window.WORD_BANK_EN = [
  /* ---------- Level 1: 2–3 letters ---------- */
  { w:"cat", lvl:1, e:"🐱", cat:"animals" },
  { w:"dog", lvl:1, e:"🐶", cat:"animals" },
  { w:"sun", lvl:1, e:"☀️", cat:"nature" },
  { w:"hat", lvl:1, e:"🎩", cat:"clothes" },
  { w:"pig", lvl:1, e:"🐷", cat:"animals" },
  { w:"cow", lvl:1, e:"🐮", cat:"animals" },
  { w:"bee", lvl:1, e:"🐝", cat:"animals" },
  { w:"ant", lvl:1, e:"🐜", cat:"animals" },
  { w:"owl", lvl:1, e:"🦉", cat:"animals" },
  { w:"fox", lvl:1, e:"🦊", cat:"animals" },
  { w:"bus", lvl:1, e:"🚌", cat:"things" },
  { w:"car", lvl:1, e:"🚗", cat:"things" },
  { w:"cup", lvl:1, e:"🥤", cat:"things" },
  { w:"box", lvl:1, e:"📦", cat:"things" },
  { w:"key", lvl:1, e:"🔑", cat:"things" },
  { w:"egg", lvl:1, e:"🥚", cat:"food", tags:["double"] },
  { w:"pen", lvl:1, e:"🖊️", cat:"school" },
  { w:"bed", lvl:1, e:"🛏️", cat:"home" },
  { w:"cake", lvl:1, e:"🎂", cat:"food" },
  { w:"ball", lvl:1, e:"⚽", cat:"toys", tags:["double"] },

  /* ---------- Level 2: short blends / 4–5 letters ---------- */
  { w:"fish", lvl:2, e:"🐟", cat:"animals" },
  { w:"frog", lvl:2, e:"🐸", cat:"animals" },
  { w:"bird", lvl:2, e:"🐦", cat:"animals" },
  { w:"duck", lvl:2, e:"🦆", cat:"animals" },
  { w:"lion", lvl:2, e:"🦁", cat:"animals" },
  { w:"bear", lvl:2, e:"🐻", cat:"animals" },
  { w:"goat", lvl:2, e:"🐐", cat:"animals" },
  { w:"tree", lvl:2, e:"🌳", cat:"nature", tags:["double"] },
  { w:"star", lvl:2, e:"⭐", cat:"nature" },
  { w:"moon", lvl:2, e:"🌙", cat:"nature" },
  { w:"rain", lvl:2, e:"🌧️", cat:"nature" },
  { w:"snow", lvl:2, e:"❄️", cat:"nature" },
  { w:"milk", lvl:2, e:"🥛", cat:"food" },
  { w:"apple", lvl:2, e:"🍎", cat:"food" },
  { w:"train", lvl:2, e:"🚂", cat:"things" },
  { w:"clock", lvl:2, e:"🕐", cat:"things" },
  { w:"brush", lvl:2, e:"🪥", cat:"home" },
  { w:"house", lvl:2, e:"🏠", cat:"home" },
  { w:"chair", lvl:2, e:"🪑", cat:"home" },
  { w:"grass", lvl:2, e:"🌱", cat:"nature", tags:["double"] },
  { w:"book", lvl:2, e:"📕", cat:"school", tags:["double"] },
  { w:"shoe", lvl:2, e:"👟", cat:"clothes" },
  { w:"kite", lvl:2, e:"🪁", cat:"toys" },
  { w:"drum", lvl:2, e:"🥁", cat:"music" },

  /* ---------- Level 3: tricky / common words ---------- */
  { w:"because", lvl:3, cat:"tricky" },
  { w:"friend", lvl:3, e:"🧑‍🤝‍🧑", cat:"tricky" },
  { w:"enough", lvl:3, cat:"tricky" },
  { w:"people", lvl:3, e:"👨‍👩‍👧‍👦", cat:"tricky" },
  { w:"school", lvl:3, e:"🏫", cat:"school" },
  { w:"water", lvl:3, e:"💧", cat:"nature" },
  { w:"tiger", lvl:3, e:"🐯", cat:"animals" },
  { w:"zebra", lvl:3, e:"🦓", cat:"animals" },
  { w:"snake", lvl:3, e:"🐍", cat:"animals" },
  { w:"horse", lvl:3, e:"🐴", cat:"animals" },
  { w:"mouse", lvl:3, e:"🐭", cat:"animals" },
  { w:"banana", lvl:3, e:"🍌", cat:"food" },
  { w:"orange", lvl:3, e:"🍊", cat:"food" },
  { w:"flower", lvl:3, e:"🌸", cat:"nature" },
  { w:"rabbit", lvl:3, e:"🐰", cat:"animals", tags:["double"] },
  { w:"rocket", lvl:3, e:"🚀", cat:"things" },
  { w:"pencil", lvl:3, e:"✏️", cat:"school" },
  { w:"garden", lvl:3, e:"🏡", cat:"home" },
  { w:"there", lvl:3, cat:"tricky", tags:["homophone"] },
  { w:"their", lvl:3, cat:"tricky", tags:["homophone"] },
  { w:"they're", lvl:3, cat:"tricky", tags:["homophone"] },
  { w:"knight", lvl:3, cat:"tricky", tags:["silent"] },
  { w:"write", lvl:3, cat:"tricky", tags:["silent"] },
  { w:"thumb", lvl:3, e:"👍", cat:"tricky", tags:["silent"] },

  /* ---------- Level 4: multi-syllable ---------- */
  { w:"elephant", lvl:4, e:"🐘", cat:"animals" },
  { w:"dinosaur", lvl:4, e:"🦕", cat:"animals" },
  { w:"butterfly", lvl:4, e:"🦋", cat:"animals" },
  { w:"crocodile", lvl:4, e:"🐊", cat:"animals" },
  { w:"beautiful", lvl:4, cat:"tricky" },
  { w:"separate", lvl:4, cat:"tricky" },
  { w:"tomorrow", lvl:4, cat:"tricky", tags:["double"] },
  { w:"favourite", lvl:4, e:"⭐", cat:"tricky" },
  { w:"chocolate", lvl:4, e:"🍫", cat:"food" },
  { w:"adventure", lvl:4, e:"🗺️", cat:"things" },
  { w:"umbrella", lvl:4, e:"☂️", cat:"things" },
  { w:"mountain", lvl:4, e:"⛰️", cat:"nature" },
  { w:"hospital", lvl:4, e:"🏥", cat:"places" },
  { w:"remember", lvl:4, cat:"tricky" },
  { w:"together", lvl:4, cat:"tricky" },
  { w:"unhappy", lvl:4, cat:"family", tags:["prefix"] },
  { w:"unlock", lvl:4, cat:"family", tags:["prefix"] },
  { w:"careful", lvl:4, cat:"family", tags:["suffix"] },
  { w:"helpful", lvl:4, cat:"family", tags:["suffix"] },
  { w:"action", lvl:4, cat:"family", tags:["suffix"] },

  /* ---------- Level 5: advanced ---------- */
  { w:"necessary", lvl:5, cat:"tricky" },
  { w:"definitely", lvl:5, cat:"tricky" },
  { w:"embarrass", lvl:5, cat:"tricky", tags:["double"] },
  { w:"rhythm", lvl:5, cat:"tricky" },
  { w:"occasion", lvl:5, cat:"tricky", tags:["double"] },
  { w:"knowledge", lvl:5, cat:"tricky", tags:["silent"] },
  { w:"question", lvl:5, e:"❓", cat:"tricky", tags:["suffix"] },
  { w:"different", lvl:5, cat:"tricky" },
  { w:"important", lvl:5, cat:"tricky" },
  { w:"dangerous", lvl:5, e:"⚠️", cat:"tricky" },
  { w:"disappear", lvl:5, cat:"family", tags:["prefix","double"] },
  { w:"wonderful", lvl:5, cat:"family", tags:["suffix"] },
  { w:"invisible", lvl:5, cat:"family", tags:["prefix"] },

  /* ---------- Level 6+: expert ---------- */
  { w:"conscience", lvl:6, cat:"tricky", tags:["silent"] },
  { w:"mischievous", lvl:6, cat:"tricky" },
  { w:"pronunciation", lvl:6, cat:"tricky" },
  { w:"onomatopoeia", lvl:6, cat:"tricky" },
  { w:"accommodate", lvl:6, cat:"tricky", tags:["double"] },
  { w:"exaggerate", lvl:6, cat:"tricky", tags:["double"] },
  { w:"parliament", lvl:6, cat:"tricky", tags:["silent"] },
  { w:"vegetable", lvl:6, e:"🥕", cat:"food" },
  { w:"temperature", lvl:6, e:"🌡️", cat:"nature" },
  { w:"extraordinary", lvl:6, cat:"tricky" }
];
